### ISSUE TITLE
PDF File

### ISSUE THREAD

**Issue by chavezgu** [JAORMX/Writing-Netfilter-Modules-Tutorial#2]
I don't think is a good idea to have the pdf binary in the repo. Specially if you have the tex source.

**Comment by JAORMX** [comment]
I uploaded it because my teammates asked me to. Originally I was only
planning to have the Tex file.

## 

Juan Antonio Osorio Robles
jaosorior@gmail.com

"All truly great thoughts are conceived by walking."
- F. N.
  On Feb 22, 2012 7:14 AM, "Gabriel Chavez" <
  reply@reply.github.com>
  wrote:
